### PR TITLE
Added fixes to some api's

### LINKED ISSUE #497: Added fixes to some api's
Added some fixes to api's before the release to the test lab

### PR DESCRIPTION
**Pull request by nardecchia-siae**
Fixes #497

### CODE REVIEW

**Comment by schiavi-siae** [comment]
Review

**Review by nardecchia-siae — COMMENTED** [review]
Please check my request

**Review by salgarello-siae — APPROVED** [review]
ok

**Review by schiavi-siae — APPROVED** [review]
ok

**Pull request merged**
